apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world  # Ensure this matches the Service selector
  template:
    metadata:
      labels:
        app: hello-world  # Must match selector
    spec:
      containers:
        - name: app
          image: gcr.io/gke-cluster-test-454517/app:latest  # Use a tag from CD pipeline
          ports:
            - containerPort: 8080
