apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  type: LoadBalancer
  selector:
    app: hello-world  # Ensure this matches the label in deployment.yaml
  ports:
    - protocol: TCP
      port: 80         # External (LoadBalancer) port
      targetPort: 8080 # Port inside the pod
